output_dir: save
overwrite_output_dir: true
do_train: true
do_eval: true
do_predict: false
evaluation_strategy: steps
prediction_loss_only: false
per_device_train_batch_size: 32
per_device_eval_batch_size: 64
per_gpu_train_batch_size: null
per_gpu_eval_batch_size: null
gradient_accumulation_steps: 1
eval_accumulation_steps: null
eval_delay: 0
learning_rate: 5.0e-05
weight_decay: 0.0
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
num_train_epochs: 6
max_steps: -1
lr_scheduler_type: linear
warmup_ratio: 0.0
warmup_steps: 0
log_level: passive
log_level_replica: passive
log_on_each_node: true
logging_dir: null
logging_strategy: steps
logging_first_step: false
logging_steps: 200
logging_nan_inf_filter: true
save_strategy: steps
save_steps: 200
save_total_limit: 5
save_on_each_node: false
no_cuda: false
seed: -1
data_seed: null
jit_mode_eval: false
use_ipex: false
bf16: false
fp16: false
fp16_opt_level: O1
half_precision_backend: auto
bf16_full_eval: false
fp16_full_eval: false
tf32: null
local_rank: -1
xpu_backend: null
tpu_num_cores: null
tpu_metrics_debug: false
debug: ''
dataloader_drop_last: false
eval_steps: 200
dataloader_num_workers: 0
past_index: -1
run_name: null
disable_tqdm: true
remove_unused_columns: true
label_names: null
load_best_model_at_end: false
metric_for_best_model: null
greater_is_better: true
ignore_data_skip: false
sharded_ddp: ''
fsdp: ''
fsdp_min_num_params: 0
fsdp_transformer_layer_cls_to_wrap: null
deepspeed: null
label_smoothing_factor: 0.0
optim: adamw_hf
adafactor: false
group_by_length: false
length_column_name: length
report_to: null
ddp_find_unused_parameters: null
ddp_bucket_cap_mb: null
dataloader_pin_memory: true
skip_memory_metrics: true
use_legacy_prediction_loop: false
push_to_hub: false
resume_from_checkpoint: null
hub_model_id: null
hub_strategy: every_save
hub_token: null
hub_private_repo: false
gradient_checkpointing: false
include_inputs_for_metrics: false
fp16_backend: auto
push_to_hub_model_id: null
push_to_hub_organization: null
push_to_hub_token: null
mp_parameters: ''
auto_find_batch_size: false
full_determinism: false
torchdynamo: null
ray_scope: last
